In [1]:
# Question 1
# Bank Account Create a class representing a bank account with attributes like account number, account holder name, and balance. Implement methods to deposit and withdraw money from the account.
class BankAccount:
    def __init__(self, account_number, account_holder, balance=0.0):
        self.account_number = account_number
        self.account_holder = account_holder
        self.balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"Deposit of {amount} successful. New balance: {self.balance}")
        else:
            print("Invalid deposit amount. Please enter a positive value.")

    def withdraw(self, amount):
        if 0 < amount <= self.balance:
            self.balance -= amount
            print(f"Withdrawal of {amount} successful. New balance: {self.balance}")
        elif amount <= 0:
            print("Invalid withdrawal amount. Please enter a positive value.")
        else:
            print("Insufficient funds for withdrawal.")

    def get_balance(self):
        return self.balance

account1 = BankAccount(account_number="123456789", account_holder="Arpan Kumar Sasmal", balance=1000.0)

account1.deposit(500.0)
account1.withdraw(200.0)
account1.withdraw(800.0)

Deposit of 500.0 successful. New balance: 1500.0
Withdrawal of 200.0 successful. New balance: 1300.0
Withdrawal of 800.0 successful. New balance: 500.0


This Python code defines a class called BankAccount that represents a simple bank account. The class has attributes such as account number, account holder name, and balance. It also includes methods to deposit money, withdraw money, and get the current balance of the account. An instance of the class is created, and various deposit and withdrawal operations are performed on that instance.

Here's an explanation of the code:

1.Class Definition: The code defines a class named BankAccount with an __init__ method to initialize the account with an account number, account holder name, and an optional initial balance.

2.Deposit Method: The deposit method is implemented to allow positive deposits into the account. If the deposited amount is positive, it is added to the account balance, and a success message is printed; otherwise, an error message is displayed.

3.Withdraw Method: The withdraw method is implemented to allow withdrawals from the account. It checks if the withdrawal amount is positive and does not exceed the available balance. If the conditions are met, the withdrawal is processed by deducting the amount from the balance. Error messages are displayed for negative withdrawal amounts or insufficient funds.

4.Get Balance Method: The get_balance method simply returns the current balance of the account.

5.Instance Creation: An instance of the BankAccount class named account1 is created with a specified account number, account holder name, and an initial balance of 1000.0.

6.Deposit Operation: A deposit of 500.0 is made into account1 using the deposit method. The new balance is printed.

7.Withdrawal Operations: Two withdrawal operations are performed on account1. First, 200.0 is withdrawn successfully, resulting in a new balance. Then, an attempt to withdraw 800.0 is made, but it fails due to insufficient funds, and an error message is displayed.

In [2]:
# Question 2
# Employee Management Create a class representing an employee with attributes like employee ID, name, and salary. Implement methods to calculate the yearly bonus and display employee details.
class Employee:
    def __init__(self, employee_id, name, salary):
        self.employee_id = employee_id
        self.name = name
        self.salary = salary

    def calculate_yearly_bonus(self, bonus_percentage):
        bonus_amount = (bonus_percentage / 100) * self.salary
        return bonus_amount

    def display_employee_details(self):
        print(f"Employee ID: {self.employee_id}")
        print(f"Name: {self.name}")
        print(f"Salary: Rs {self.salary}")
        print()

employee1 = Employee(employee_id=1, name="Arpan", salary=500000.0)

employee1.display_employee_details()

bonus_percentage = 10 
yearly_bonus = employee1.calculate_yearly_bonus(bonus_percentage)
print(f"Yearly Bonus: Rs {yearly_bonus}")

Employee ID: 1
Name: Arpan
Salary: Rs 500000.0

Yearly Bonus: Rs 50000.0


This Python code defines a class named Employee to represent an employee with attributes such as employee ID, name, and salary. The class includes methods to calculate the yearly bonus based on a given percentage and to display the employee details. An instance of the class is created, and its details, along with the calculated yearly bonus, are displayed.

Here's an explanation of the code:

1.Class Definition: The code defines a class named Employee with an __init__ method to initialize the employee with an employee ID, name, and salary.

2.Initialization: An instance of the Employee class named employee1 is created with specific values for employee ID, name, and salary.

3.Display Employee Details: The display_employee_details method is called on the employee1 instance, which prints the employee ID, name, and salary.

4.Bonus Calculation Method: The calculate_yearly_bonus method takes a bonus percentage as input, calculates the bonus amount based on the employee's salary, and returns the bonus amount.

5.Bonus Percentage: A bonus percentage of 10% is assigned to the variable bonus_percentage.

6.Yearly Bonus Calculation: The calculate_yearly_bonus method is called on the employee1 instance with the provided bonus percentage. The calculated yearly bonus is stored in the variable yearly_bonus.

7.Print Employee Details: The employee details are printed using the display_employee_details method, providing information about the employee's ID, name, and salary.

8.Print Yearly Bonus: The calculated yearly bonus is printed, indicating the bonus amount in Indian Rupees (Rs).

In [4]:
# Question 3
# Vehicle Rental Create a class representing a vehicle rental system. Implement methods to rent a vehicle, return a vehicle, and display available vehicles.
class Vehicle:
    def __init__(self, vehicle_id, model, rental_rate, is_available=True):
        self.vehicle_id = vehicle_id
        self.model = model
        self.rental_rate = rental_rate
        self.is_available = is_available

    def rent_vehicle(self):
        if self.is_available:
            self.is_available = False
            print(f"Vehicle {self.vehicle_id} ({self.model}) rented successfully.")
        else:
            print(f"Vehicle {self.vehicle_id} ({self.model}) is not available for rent.")

    def return_vehicle(self):
        if not self.is_available:
            self.is_available = True
            print(f"Vehicle {self.vehicle_id} ({self.model}) returned successfully.")
        else:
            print(f"Vehicle {self.vehicle_id} ({self.model}) is already available.")

class VehicleRentalSystem:
    def __init__(self):
        self.vehicles = []

    def add_vehicle(self, vehicle):
        self.vehicles.append(vehicle)

    def display_available_vehicles(self):
        print("Available Vehicles:")
        for vehicle in self.vehicles:
            if vehicle.is_available:
                print(f"{vehicle.model} (ID: {vehicle.vehicle_id}) - Rental Rate: Rs {vehicle.rental_rate} per day")
        print()

# Example usage:
vehicle1 = Vehicle(vehicle_id=1, model="Sedan", rental_rate=50.0)
vehicle2 = Vehicle(vehicle_id=2, model="SUV", rental_rate=70.0)

rental_system = VehicleRentalSystem()
rental_system.add_vehicle(vehicle1)
rental_system.add_vehicle(vehicle2)

rental_system.display_available_vehicles()

vehicle1.rent_vehicle()
rental_system.display_available_vehicles()

vehicle2.rent_vehicle()
rental_system.display_available_vehicles()

vehicle1.return_vehicle()
rental_system.display_available_vehicles()

Available Vehicles:
Sedan (ID: 1) - Rental Rate: Rs 50.0 per day
SUV (ID: 2) - Rental Rate: Rs 70.0 per day

Vehicle 1 (Sedan) rented successfully.
Available Vehicles:
SUV (ID: 2) - Rental Rate: Rs 70.0 per day

Vehicle 2 (SUV) rented successfully.
Available Vehicles:

Vehicle 1 (Sedan) returned successfully.
Available Vehicles:
Sedan (ID: 1) - Rental Rate: Rs 50.0 per day



This Python code creates a basic vehicle rental system, allowing the addition of vehicles, display of available vehicles, and simulation of rental and return operations. The example usage at the end demonstrates the interaction with the system and the impact on the availability status of vehicles.

Here's an explanation of the code:

1.Vehicle Class Definition: The code defines a Vehicle class with an __init__ method to initialize vehicle attributes such as ID, model, rental rate, and availability status. It also includes methods to rent and return the vehicle.

2.VehicleRentalSystem Class Definition: The VehicleRentalSystem class is defined to manage a list of vehicles. It includes methods to add vehicles, display available vehicles, and interact with individual vehicles.

3.Vehicle Instances Creation: Two instances of the Vehicle class (vehicle1 and vehicle2) are created with specific details such as ID, model, and rental rate.

4.VehicleRentalSystem Instance Creation: An instance of the VehicleRentalSystem class (rental_system) is created to manage and interact with vehicles.

5.Adding Vehicles to Rental System: The add_vehicle method is used to add vehicle1 and vehicle2 to the rental_system.

6.Display Available Vehicles: The display_available_vehicles method is called on the rental_system to show the available vehicles along with their rental rates.

7.Renting and Returning Vehicles: The rent_vehicle method is called on vehicle1 and vehicle2 to simulate renting. The availability status is updated accordingly. Then, the return_vehicle method is called on vehicle1 to simulate returning the vehicle.

8.Displaying Available Vehicles After Operations: The display_available_vehicles method is called after each operation to show the updated list of available vehicles, reflecting the changes made during the rental and return operations.

In [5]:
# Question 4
# Library Catalog Create classes representing a library and a book. Implement methods to add books to the library, borrow books, and display available books.
class Book:
    def __init__(self, book_id, title, author):
        self.book_id = book_id
        self.title = title
        self.author = author
        self.is_available = True

    def borrow_book(self):
        if self.is_available:
            self.is_available = False
            print(f"Book '{self.title}' by {self.author} (ID: {self.book_id}) borrowed successfully.")
        else:
            print(f"Book '{self.title}' is not available for borrowing.")

    def return_book(self):
        if not self.is_available:
            self.is_available = True
            print(f"Book '{self.title}' by {self.author} (ID: {self.book_id}) returned successfully.")
        else:
            print(f"Book '{self.title}' is already available in the library.")

class Library:
    def __init__(self):
        self.books = []

    def add_book(self, book):
        self.books.append(book)

    def display_available_books(self):
        print("Available Books:")
        for book in self.books:
            if book.is_available:
                print(f"{book.title} by {book.author} (ID: {book.book_id})")
        print()

book1 = Book(book_id=1, title="The Catcher in the Rye", author="J.D. Salinger")
book2 = Book(book_id=2, title="To Kill a Mockingbird", author="Harper Lee")

library = Library()
library.add_book(book1)
library.add_book(book2)

library.display_available_books()

book1.borrow_book()
library.display_available_books()

book2.borrow_book()
library.display_available_books()

book1.return_book()
library.display_available_books()

Available Books:
The Catcher in the Rye by J.D. Salinger (ID: 1)
To Kill a Mockingbird by Harper Lee (ID: 2)

Book 'The Catcher in the Rye' by J.D. Salinger (ID: 1) borrowed successfully.
Available Books:
To Kill a Mockingbird by Harper Lee (ID: 2)

Book 'To Kill a Mockingbird' by Harper Lee (ID: 2) borrowed successfully.
Available Books:

Book 'The Catcher in the Rye' by J.D. Salinger (ID: 1) returned successfully.
Available Books:
The Catcher in the Rye by J.D. Salinger (ID: 1)



This Python code creates a basic library catalog system allowing the addition of books, display of available books, and simulation of borrowing and returning operations. The example usage at the end demonstrates the interaction with the library system and the impact on the availability status of books.

Here's an explanation of the code:

1.Book Class Definition: The Book class is defined with an __init__ method to initialize book attributes such as ID, title, author, and availability status. It also includes methods to borrow and return the book.

2.Library Class Definition: The Library class is defined with an __init__ method to initialize an empty list of books. It includes methods to add books to the library, display available books, and interact with individual books.

3.Book Instances Creation: Two instances of the Book class (book1 and book2) are created with specific details such as ID, title, and author.

4.Library Instance Creation: An instance of the Library class (library) is created to manage and interact with books.

5.Adding Books to Library: The add_book method is used to add book1 and book2 to the library.

6.Display Available Books: The display_available_books method is called on the library to show the available books.

7.Borrowing and Returning Books: The borrow_book method is called on book1 and book2 to simulate borrowing. The availability status is updated accordingly. Then, the return_book method is called on book1 to simulate returning the book.

8.Displaying Available Books After Operations: The display_available_books method is called after each operation to show the updated list of available books, reflecting the changes made during the borrow and return operations.

In [7]:
# Question 5
# Product Inventory Create classes representing a product and an inventory system. Implement methods to add products to the inventory, update product quantity, and display available products.
class Product:
    def __init__(self, product_id, name, price, quantity):
        self.product_id = product_id
        self.name = name
        self.price = price
        self.quantity = quantity

class InventorySystem:
    def __init__(self):
        self.products = []

    def add_product(self, product):
        self.products.append(product)
        print(f"Product '{product.name}' (ID: {product.product_id}) added to the inventory.")

    def update_quantity(self, product_id, new_quantity):
        for product in self.products:
            if product.product_id == product_id:
                product.quantity = new_quantity
                print(f"Quantity for product '{product.name}' updated to {new_quantity}.")
                return
        print(f"Product with ID {product_id} not found in the inventory.")

    def display_available_products(self):
        print("Available Products:")
        for product in self.products:
            print(f"{product.name} (ID: {product.product_id}) - Price: Rs {product.price} - Quantity: {product.quantity}")
        print()

product1 = Product(product_id=1, name="Laptop", price=800.0, quantity=10)
product2 = Product(product_id=2, name="Smartphone", price=300.0, quantity=20)

inventory_system = InventorySystem()
inventory_system.add_product(product1)
inventory_system.add_product(product2)

inventory_system.display_available_products()

inventory_system.update_quantity(product_id=1, new_quantity=8)
inventory_system.display_available_products()

inventory_system.update_quantity(product_id=3, new_quantity=15)

Product 'Laptop' (ID: 1) added to the inventory.
Product 'Smartphone' (ID: 2) added to the inventory.
Available Products:
Laptop (ID: 1) - Price: Rs 800.0 - Quantity: 10
Smartphone (ID: 2) - Price: Rs 300.0 - Quantity: 20

Quantity for product 'Laptop' updated to 8.
Available Products:
Laptop (ID: 1) - Price: Rs 800.0 - Quantity: 8
Smartphone (ID: 2) - Price: Rs 300.0 - Quantity: 20

Product with ID 3 not found in the inventory.


This Python code creates a basic product inventory system allowing the addition of products, updating product quantities, and displaying available products. The example usage at the end demonstrates the interaction with the inventory system and the impact on product quantities.

Here's an explanation of the code:

1.Product Class Definition: The Product class is defined with an __init__ method to initialize product attributes such as ID, name, price, and quantity.

2.InventorySystem Class Definition: The InventorySystem class is defined with an __init__ method to initialize an empty list of products. It includes methods to add products to the inventory, update product quantity, and display available products.

3.Product Instances Creation: Two instances of the Product class (product1 and product2) are created with specific details such as ID, name, price, and quantity.

4.InventorySystem Instance Creation: An instance of the InventorySystem class (inventory_system) is created to manage and interact with products.

5.Adding Products to Inventory: The add_product method is used to add product1 and product2 to the inventory_system.

6.Display Available Products: The display_available_products method is called on the inventory_system to show the available products.

7.Updating Product Quantity: The update_quantity method is called to update the quantity of product1 to a new quantity of 8. The update is confirmed by displaying available products.

8.Updating Nonexistent Product Quantity: The update_quantity method is called with a non-existent product ID (3), and a message is displayed indicating that the product was not found in the inventory.

In [8]:
# Question 6
# Shape Calculation Create a class representing a shape with attributes like length, width, and height. Implement methods to calculate the area and perimeter of the shape.
class Shape:
    def __init__(self, length, width=None, height=None):
        self.length = length
        self.width = width
        self.height = height

    def calculate_area(self):
        raise NotImplementedError("Subclasses must implement the calculate_area method")

    def calculate_perimeter(self):
        raise NotImplementedError("Subclasses must implement the calculate_perimeter method")

class Rectangle(Shape):
    def __init__(self, length, width):
        super().__init__(length, width)

    def calculate_area(self):
        return self.length * self.width

    def calculate_perimeter(self):
        return 2 * (self.length + self.width)

class Square(Rectangle):
    def __init__(self, side):
        super().__init__(length=side, width=side)

rectangle = Rectangle(length=5, width=3)
square = Square(side=4)

print("Rectangle Area:", rectangle.calculate_area())
print("Rectangle Perimeter:", rectangle.calculate_perimeter())

print("Square Area:", square.calculate_area())
print("Square Perimeter:", square.calculate_perimeter())

Rectangle Area: 15
Rectangle Perimeter: 16
Square Area: 16
Square Perimeter: 16


This Python code provides a flexible and extensible framework for representing and calculating the area and perimeter of various shapes. The example usage illustrates the application of this framework with specific instances of rectangles and squares.

Here's an explanation of the code:

1.Shape Class Definition: The Shape class is defined with an __init__ method to initialize common attributes like length, width, and height. It also includes methods calculate_area and calculate_perimeter with NotImplementedError, indicating that subclasses must implement these methods.

2.Rectangle Class Definition: The Rectangle class is a subclass of Shape and extends it by implementing the calculate_area and calculate_perimeter methods specifically for rectangles. It also overrides the __init__ method to provide a specialized constructor for rectangles.

3.Square Class Definition: The Square class is a subclass of Rectangle and inherits its behavior. It overrides the constructor to provide a specialized constructor for squares, ensuring that the length and width are always the same.

4.Rectangle Instance Creation: An instance of the Rectangle class named rectangle is created with a length of 5 and a width of 3.

5.Square Instance Creation: An instance of the Square class named square is created with a side length of 4.

6.Calculate and Print Rectangle Area and Perimeter: The area and perimeter of the rectangle instance are calculated and printed.

7.Calculate and Print Square Area and Perimeter: The area and perimeter of the square instance are calculated and printed.

8.Inheritance and Polymorphism: The code demonstrates the principles of inheritance and polymorphism, where subclasses inherit behavior from the base class (Shape), and polymorphism allows the use of a common interface (calculate_area and calculate_perimeter) for different shapes.

In [9]:
# Question 7
# Student Management Create a class representing a student with attributes like student ID, name, and grades. Implement methods to calculate the average grade and display student details.
class Student:
    def __init__(self, student_id, name):
        self.student_id = student_id
        self.name = name
        self.grades = []

    def add_grade(self, grade):
        self.grades.append(grade)

    def calculate_average_grade(self):
        if not self.grades:
            return 0.0
        return sum(self.grades) / len(self.grades)

    def display_student_details(self):
        print(f"Student ID: {self.student_id}")
        print(f"Name: {self.name}")
        print(f"Grades: {', '.join(map(str, self.grades))}")
        print(f"Average Grade: {self.calculate_average_grade():.2f}")
        print()

# Example usage:
student1 = Student(student_id="S001", name="Arpan")
student1.add_grade(85)
student1.add_grade(92)
student1.add_grade(78)

student2 = Student(student_id="S002", name="Akash")
student2.add_grade(90)
student2.add_grade(88)
student2.add_grade(95)

student1.display_student_details()
student2.display_student_details()

Student ID: S001
Name: Arpan
Grades: 85, 92, 78
Average Grade: 85.00

Student ID: S002
Name: Akash
Grades: 90, 88, 95
Average Grade: 91.00



This Python code provides a simple student management system allowing the addition of grades, calculation of average grades, and display of student details. The example usage demonstrates the application of this system with specific instances of students and their grades.

Here's an explanation of the code:

1.Student Class Definition: The Student class is defined with an __init__ method to initialize student attributes such as student ID, name, and an empty list for grades. It includes methods add_grade to add grades to the student's list, calculate_average_grade to compute the average of the grades, and display_student_details to print the student's information.

2.Student Instances Creation: Two instances of the Student class (student1 and student2) are created with specific details such as student ID and name.

3.Adding Grades: Grades are added to each student using the add_grade method.

4.Calculate Average Grade: The calculate_average_grade method is called on each student to compute their average grade.

5.Displaying Student Details: The display_student_details method is called on each student to print their student ID, name, list of grades, and average grade.

6.Example Usage for Student1: For student1, the student ID is "S001," the name is "Arpan," and grades 85, 92, and 78 are added. The average grade is then calculated and displayed.

7.Example Usage for Student2: For student2, the student ID is "S002," the name is "Akash," and grades 90, 88, and 95 are added. The average grade is then calculated and displayed.

8.Printed Output: The printed output includes the student details for both student1 and student2, displaying student ID, name, grades, and the calculated average grade.

In [11]:
# Question 8
# Email Management Create a class representing an email with attributes like sender, recipient, and subject. Implement methods to send an email and display email details.
class Email:
    def __init__(self, sender, recipient, subject, body):
        self.sender = sender
        self.recipient = recipient
        self.subject = subject
        self.body = body
        self.is_sent = False

    def send_email(self):
        if not self.is_sent:
            print(f"Email sent from {self.sender} to {self.recipient}")
            self.is_sent = True
        else:
            print("This email has already been sent.")

    def display_email_details(self):
        print("Email Details:")
        print(f"Sender: {self.sender}")
        print(f"Recipient: {self.recipient}")
        print(f"Subject: {self.subject}")
        print(f"Body: {self.body}")
        print(f"Status: {'Sent' if self.is_sent else 'Not Sent'}")
        print()

email1 = Email(sender="akash@example.com", recipient="arpan@example.com", subject="Meeting Tomorrow", body="Hi Arpan, let's meet tomorrow at 2 PM.")

email1.display_email_details()
email1.send_email()
email1.display_email_details()

Email Details:
Sender: akash@example.com
Recipient: arpan@example.com
Subject: Meeting Tomorrow
Body: Hi Arpan, let's meet tomorrow at 2 PM.
Status: Not Sent

Email sent from akash@example.com to arpan@example.com
Email Details:
Sender: akash@example.com
Recipient: arpan@example.com
Subject: Meeting Tomorrow
Body: Hi Arpan, let's meet tomorrow at 2 PM.
Status: Sent



This Python code provides a simple email management system allowing the creation of email instances, sending emails, and displaying email details. The example usage demonstrates the application of this system with a specific email instance.

Here's an explanation of the code:

1.Email Class Definition: The Email class is defined with an __init__ method to initialize email attributes such as sender, recipient, subject, body, and the status flag is_sent. It includes methods send_email to simulate sending an email and display_email_details to print the email information.

2.Email Instance Creation: An instance of the Email class (email1) is created with specific details such as sender, recipient, subject, and body.

3.Display Email Details (Before Sending): The display_email_details method is called on email1 to print the email details, including sender, recipient, subject, body, and the current status (not sent).

4.Sending the Email: The send_email method is called on email1 to simulate sending the email. If the email has not been sent before, it prints a message indicating that the email has been sent and updates the status to "Sent."

5.Display Email Details (After Sending): The display_email_details method is called again on email1 to print the updated email details, including the new status ("Sent").

6.Example Usage Details for Email1: For email1, the sender is "akash@example.com," the recipient is "arpan@example.com," the subject is "Meeting Tomorrow," and the body contains a meeting invitation. The email is displayed, then sent, and the updated details are displayed.

7.Printed Output: The printed output includes the email details both before and after sending, showing the sender, recipient, subject, body, and the status of the email.

In [12]:
# Question 9
# Social Media Profile Create a class representing a social media profile with attributes like username and posts. Implement methods to add posts, display posts, and search for posts by keyword.
class SocialMediaProfile:
    def __init__(self, username):
        self.username = username
        self.posts = []

    def add_post(self, post_content):
        self.posts.append(post_content)
        print(f"Post added to {self.username}'s profile.")

    def display_posts(self):
        print(f"Posts from {self.username}'s profile:")
        for post in self.posts:
            print(post)
        print()

    def search_posts(self, keyword):
        matching_posts = [post for post in self.posts if keyword.lower() in post.lower()]
        if matching_posts:
            print(f"Posts containing '{keyword}':")
            for post in matching_posts:
                print(post)
        else:
            print(f"No posts containing '{keyword}' found.")
        print()

# Example usage:
profile1 = SocialMediaProfile(username="ArpanSasmal")
profile1.add_post("Enjoying a beautiful day at the park!")
profile1.add_post("Trying out a new recipe for dinner.")

profile2 = SocialMediaProfile(username="AkashDas")
profile2.add_post("Excited for the weekend getaway!")
profile2.add_post("Reading a fascinating book.")

profile1.display_posts()
profile2.display_posts()

profile1.search_posts(keyword="recipe")
profile2.search_posts(keyword="weekend")
profile2.search_posts(keyword="workout")

Post added to ArpanSasmal's profile.
Post added to ArpanSasmal's profile.
Post added to AkashDas's profile.
Post added to AkashDas's profile.
Posts from ArpanSasmal's profile:
Enjoying a beautiful day at the park!
Trying out a new recipe for dinner.

Posts from AkashDas's profile:
Excited for the weekend getaway!
Reading a fascinating book.

Posts containing 'recipe':
Trying out a new recipe for dinner.

Posts containing 'weekend':
Excited for the weekend getaway!

No posts containing 'workout' found.



This Python code provides a basic representation of social media profiles, allowing the addition of posts, display of all posts, and searching for posts containing specific keywords. The example usage demonstrates the application of this system with two profile instances and the associated posts.

Here's an explanation of the code:

1.SocialMediaProfile Class Definition: The SocialMediaProfile class is defined with an __init__ method to initialize attributes such as the username and an empty list for posts. It includes methods add_post to add posts, display_posts to print all posts, and search_posts to find and display posts containing a specific keyword.

2.Profile Instances Creation: Two instances of the SocialMediaProfile class (profile1 and profile2) are created with specific usernames.

3.Adding Posts to Profiles: Posts are added to each profile using the add_post method, simulating the addition of social media posts.

4.Displaying Posts for Each Profile: The display_posts method is called on each profile to print all posts associated with that profile.

5.Example Posts for Profile1: For profile1, posts are added, such as "Enjoying a beautiful day at the park!" and "Trying out a new recipe for dinner."

6.Example Posts for Profile2: For profile2, posts are added, such as "Excited for the weekend getaway!" and "Reading a fascinating book."

7.Search Posts Containing a Keyword (Profile1): The search_posts method is called on profile1 to find and display posts containing the keyword "recipe."

8.Search Posts Containing a Keyword (Profile2): The search_posts method is called on profile2 to find and display posts containing the keywords "weekend" and "workout."

In [13]:
# Question 10
# ToDo List Create a class representing a ToDo list with attributes like tasks and due dates. Implement methods to add tasks, mark tasks as completed, and display pending tasks.
from datetime import datetime

class Task:
    def __init__(self, description, due_date=None):
        self.description = description
        self.due_date = due_date
        self.completed = False

class ToDoList:
    def __init__(self):
        self.tasks = []

    def add_task(self, task_description, due_date=None):
        task = Task(description=task_description, due_date=due_date)
        self.tasks.append(task)
        print(f"Task '{task_description}' added to the ToDo list.")

    def mark_task_completed(self, task_description):
        for task in self.tasks:
            if task.description == task_description:
                task.completed = True
                print(f"Task '{task_description}' marked as completed.")
                return
        print(f"Task '{task_description}' not found in the ToDo list.")

    def display_pending_tasks(self):
        pending_tasks = [task for task in self.tasks if not task.completed]
        if pending_tasks:
            print("Pending Tasks:")
            for task in pending_tasks:
                due_date_info = f" (Due Date: {task.due_date})" if task.due_date else ""
                print(f"- {task.description}{due_date_info}")
        else:
            print("No pending tasks.")
        print()

todo_list = ToDoList()

todo_list.add_task("Complete project")
todo_list.add_task("Prepare for meeting", due_date=datetime(2023, 11, 30))
todo_list.add_task("Exercise")

todo_list.display_pending_tasks()

todo_list.mark_task_completed("Prepare for meeting")

todo_list.display_pending_tasks()

Task 'Complete project' added to the ToDo list.
Task 'Prepare for meeting' added to the ToDo list.
Task 'Exercise' added to the ToDo list.
Pending Tasks:
- Complete project
- Prepare for meeting (Due Date: 2023-11-30 00:00:00)
- Exercise

Task 'Prepare for meeting' marked as completed.
Pending Tasks:
- Complete project
- Exercise



This Python code provides a basic implementation of a ToDo list, allowing the addition of tasks, marking tasks as completed, and displaying pending tasks. The example usage demonstrates the application of this system with a specific instance of a ToDo list and associated tasks.

Here's an explanation of the code:

1.Task Class Definition: The Task class is defined with an __init__ method to initialize task attributes such as description, due date, and completion status.

2.ToDoList Class Definition: The ToDoList class is defined with an __init__ method to initialize an empty list of tasks. It includes methods add_task to add tasks to the list, mark_task_completed to update the completion status of a task, and display_pending_tasks to print pending tasks.

3.ToDoList Instance Creation: An instance of the ToDoList class (todo_list) is created to manage and interact with tasks.

4.Adding Tasks to ToDoList: Tasks are added to the todo_list using the add_task method. Specific tasks are added, such as "Complete project," "Prepare for meeting" (with a due date), and "Exercise."

5.Displaying Pending Tasks (Before Completion): The display_pending_tasks method is called on the todo_list to print the pending tasks, including their descriptions and, if applicable, due dates.

6.Marking a Task as Completed: The mark_task_completed method is called on the todo_list to mark the task "Prepare for meeting" as completed.

7.Displaying Pending Tasks (After Completion): The display_pending_tasks method is called again on the todo_list to print the updated list of pending tasks, excluding the completed task.

8.Printed Output: The printed output includes the list of pending tasks before and after marking a task as completed, showing the descriptions and due dates (if available).